#!/bin/bash

start() {
	sh /home/ubuntu/tomcat/bin/startup.sh
}

stop() {
	sh /home/ubuntu/tomcat/bin/shutdown.sh
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: {start|stop|restart}"
		exit 1
		;;
esac

exit $?
